import ContentContainer from "@/app/(protected)/_components/content-container"
import { ContentLayout } from "@/app/(protected)/_components/content-layout"
import Breadcrumbs from "@/components/breadcrumbs"
import PageWrapper from "@/app/(protected)/_components/page-wrapper"
import { Card } from "@/components/ui/card"
import SupplierLists from "./_components/supplier-list"
import { getBpMasters } from "@/actions/bp-master"
import { getSyncMetaByCode } from "@/actions/sync-meta"
import SupplierListHeader from "./_components/supplier-list-header"
import { Icons } from "@/components/icons"

export default async function SuppliersPage() {
  const [syncMeta] = await Promise.all([getSyncMetaByCode("S"), getBpMasters({ cardType: "S" })])

  const suppliers = [
    {
      Address: null,
      CardCode: "V10002",
      CardName: "Nanotech Electromechanical Solutions",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240804",
      Currency: "USD",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240804",
      ZipCode: null,
      syncStatus: "synced",
    },
    {
      Address: null,
      CardCode: "V10000",
      CardName: "I-Con Tech. Int'l Incorporated",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240803",
      Currency: "USD",
      GroupCode: 109,
      GroupName: "General Supplies",
      GroupNum: 14,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "NET90",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240803",
      ZipCode: null,
    },
    {
      Address: "No.68 Wang Lung Street",
      CardCode: "V013",
      CardName: "Wuhan P&S",
      CardType: "S",
      CntctPrsn: "Buyer",
      CreateDate: "20240925",
      Currency: "USD",
      GroupCode: 107,
      GroupName: "Semi-Conductors",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240925",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10003",
      CardName: "Greenfield Corporate Center",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240804",
      Currency: "PHP",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240804",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10010",
      CardName: "Royal Cablevision Corporation",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240807",
      Currency: "PHP",
      GroupCode: 116,
      GroupName: "Utilities",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240807",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10008",
      CardName: "Bureau of Internal Revenue",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240804",
      Currency: "PHP",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240804",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10011",
      CardName: "HR Online Philippines",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240808",
      Currency: "PHP",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240808",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10009",
      CardName: "A2Z Logistics Inc. (PHP)",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240804",
      Currency: "PHP",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240804",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10005",
      CardName: "Home Development Mutual Fund",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240804",
      Currency: "PHP",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240804",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10004",
      CardName: "Social Security System",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240804",
      Currency: "PHP",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240804",
      ZipCode: null,
    },
    {
      Address: "Street",
      CardCode: "V10006",
      CardName: "DHL Express (Philippines) Corp.",
      CardType: "S",
      CntctPrsn: "Pres",
      CreateDate: "20240804",
      Currency: "PHP",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: "Street",
      MailZipCod: "Zip",
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240924",
      ZipCode: "Zip",
    },
    {
      Address: null,
      CardCode: "54000",
      CardName: "HK Galaxy IC",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240820",
      Currency: "PHP",
      GroupCode: 120,
      GroupName: "Broker Excess",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240820",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10007",
      CardName: "A2Z Logistics Inc (USD)",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240804",
      Currency: "USD",
      GroupCode: 101,
      GroupName: "Vendor (non-semiconductor)",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240804",
      ZipCode: null,
    },
    {
      Address: "Santa Rosa Laguna Arcadia",
      CardCode: "V123",
      CardName: "Testing Supplier",
      CardType: "S",
      CntctPrsn: "Testing",
      CreateDate: "20240823",
      Currency: "##",
      GroupCode: 107,
      GroupName: "Semi-Conductors",
      GroupNum: 12,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "NET7",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240823",
      ZipCode: null,
    },
    {
      Address: null,
      CardCode: "V10001",
      CardName: "Leopard Connectivity Business Solutions Inc.",
      CardType: "S",
      CntctPrsn: null,
      CreateDate: "20240803",
      Currency: "PHP",
      GroupCode: 120,
      GroupName: "Broker Excess",
      GroupNum: 1,
      MailAddres: null,
      MailZipCod: null,
      Phone1: null,
      PymntGroup: "COD",
      U_OMEG_QBRelated: null,
      U_VendorCode: null,
      UpdateDate: "20240803",
      ZipCode: null,
    },
  ] as any[]

  return (
    <ContentLayout title='Suppliers'>
      <Breadcrumbs
        items={[
          { label: "Home", href: "/" },
          { label: "Dashboard", href: "/dashboard" },
          { label: "Master Data" },
          { label: "Suppliers", isPage: true },
        ]}
      />

      <ContentContainer>
        <PageWrapper
          title='Suppliers'
          description='Manage and track your suppliers effectively'
          defaultAction={{
            label: "Add Supplier",
            href: "/dashboard/master-data/suppliers/add",
            icon: Icons.plus,
          }}
        >
          {syncMeta && (
            <Card className='rounded-lg p-6 shadow-md'>
              <SupplierListHeader syncMeta={syncMeta} />
            </Card>
          )}

          <Card className='rounded-lg p-6 shadow-md'>
            <SupplierLists suppliers={suppliers} />
          </Card>
        </PageWrapper>
      </ContentContainer>
    </ContentLayout>
  )
}
