import {
  ArrowLeft,
  Check,
  CheckCircle2,
  CircleAlertIcon,
  Folder,
  Handshake,
  Inbox,
  Info,
  LayoutGrid,
  Loader2,
  LogIn,
  LucideIcon,
  MoonIcon,
  Settings,
  Sheet,
  SunIcon,
  TriangleAlert,
  Users,
  Watch,
  Plus,
  X,
  Search,
  RefreshCw,
  PlusCircle,
  Pencil,
  Trash,
  FileText,
  Lock,
  BarChart2,
  Calendar,
  History,
  Wallet,
  Truck,
  DollarSign,
  FolderClosed,
  FileBarChart2,
  Store,
  UserCheck,
  Receipt,
  PiggyBank,
  Paperclip,
  ClipboardEdit,
  ShoppingBag,
  ShoppingCart,
  Shapes,
  Box,
  Boxes,
  PackageCheck,
  FileEdit,
  Clock,
  ClipboardList,
  Copy,
  Shield,
  ShieldCheck,
  AlertCircle,
  QrCode,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  MoreHorizontal,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  EyeOff,
  Settings2,
  FunnelIcon,
  Send,
  MailPlus,
  MailMinus,
  Blocks,
  FilePlus,
  FileMinus,
  LandPlot,
  Mail,
  UserPlus,
  UserMinus,
  CalendarClock,
  NotebookPen,
  ExternalLink,
  Link,
  CircleUser,
  Eye,
  MoreVertical,
  Phone,
  ThumbsUp,
  ThumbsDown,
  ShieldClose,
  Globe,
  Database,
  UserRoundCog,
  Construction,
  XCircle,
  Hash,
  CalendarCheck,
  Printer,
  Download,
  CircleCheckBig,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  qrCode: QrCode,
  watch: Watch,
  info: Info,
  triangleAlert: TriangleAlert,
  circleAlert: CircleAlertIcon,
  checkCircle: CheckCircle2,
  checkCircleBig: CircleCheckBig,
  xCicle: XCircle,
  spinner: Loader2,
  sun: SunIcon,
  moon: MoonIcon,
  dashboard: LayoutGrid,
  circleUser: CircleUser,
  users: Users,
  cicleUser: CircleUser,
  settings: Settings,
  table: Sheet,
  folder: Folder,
  handeShake: Handshake,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldClose: ShieldClose,
  alertCircle: AlertCircle,
  check: Check,
  inbox: Inbox,
  login: LogIn,
  plus: Plus,
  pencil: Pencil,
  trash: Trash,
  search: Search,
  refreshCw: RefreshCw,
  plusCircle: PlusCircle,
  x: X,
  fileText: FileText,
  lock: Lock,
  report: BarChart2,
  calendar: Calendar,
  calendarClock: CalendarClock,
  calendarCheck: CalendarCheck,
  history: History,
  wallet: Wallet,
  truck: Truck,
  cirleDollar: DollarSign,
  folderClosed: FolderClosed,
  squareActivity: FileBarChart2,
  store: Store,
  contact: UserCheck,
  receipt: Receipt,
  commision: PiggyBank,
  paperClip: Paperclip,
  notepadText: FileText,
  notebookPen: NotebookPen,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  shapes: Shapes,
  boxes: Boxes,
  box: Box,
  shoppingBaskt: ShoppingBag,
  files: FileText,
  sheet: Sheet,
  clock: Clock,
  clipboardPen: ClipboardEdit,
  dollar: DollarSign,
  copy: Copy,
  chevUp: ChevronUp,
  chevDown: ChevronDown,
  chevLeft: ChevronLeft,
  chevRight: ChevronRight,
  chevUpDown: ChevronsUpDown,
  doubleChevLeft: ChevronsLeft,
  doubleChevRight: ChevronsRight,
  doubleChevUp: ChevronsUp,
  doubleChevDown: ChevronsDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  eyeOff: EyeOff,
  eye: Eye,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  adjustmentHorizontal: Settings2,
  funnel: FunnelIcon,
  send: Send,
  mailPlus: MailPlus,
  mailMinus: MailMinus,
  mail: Mail,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  blocks: Blocks,
  landPlot: LandPlot,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userRoundCog: UserRoundCog,
  externalLink: ExternalLink,
  link: Link,
  phone: Phone,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  globe: Globe,
  database: Database,
  construction: Construction,
  hash: Hash,
  print: Printer,
  download: Download,
}
