import {
  ArrowLeft,
<<<<<<< HEAD
  Check,
=======
  Banknote,
  Blocks,
  Boxes,
  Calendar,
  ChartNoAxesCombined,
>>>>>>> 8312d78f775457b87697f2a6ebd91d46b2676e01
  CheckCircle2,
  CircleAlertIcon,
  CircleDollarSign,
  ClipboardPen,
  Clock,
  Contact,
  DollarSign,
  Files,
  FileText,
  Folder,
  FolderClosed,
  Handshake,
  History,
  Inbox,
  Info,
  LayoutGrid,
  Loader2,
<<<<<<< HEAD
  LogIn,
=======
  LockKeyhole,
>>>>>>> 8312d78f775457b87697f2a6ebd91d46b2676e01
  LucideIcon,
  MoonIcon,
  NotepadText,
  Paperclip,
  Plus,
  Receipt,
  ReceiptText,
  Settings,
  Shapes,
  Sheet,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  SquareActivity,
  Store,
  SunIcon,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Users,
  Wallet,
  Watch
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  watch: Watch,
  info: Info,
  triangleAlert: TriangleAlert,
  circleAlert: CircleAlertIcon,
  checkCircle: CheckCircle2,
  spinner: Loader2,
  sun: SunIcon,
  moon: MoonIcon,
  dashboard: LayoutGrid,
  users: Users,
  settings: Settings,
  table: Sheet,
  folder: Folder,
  folderClosed: FolderClosed,
  handeShake: Handshake,
  inbox: Inbox,
  arrowLeft: ArrowLeft,
<<<<<<< HEAD
  check: Check,
  login: LogIn
=======
  lock: LockKeyhole,
  report: ChartNoAxesCombined,
  calendar: Calendar,
  history: History,
  wallet: Wallet,
  truck: Truck,
  boxes: Boxes,
  fileText: FileText,
  cirleDollar: CircleDollarSign,
  squareActivity: SquareActivity,
  contact: Contact,
  receipt: Receipt,
  receiptText: ReceiptText,
  commision: Banknote,
  paperClip: Paperclip,
  notepadText: NotepadText,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  shoppingBaskt: ShoppingBasket,
  shapes: Shapes,
  store: Store,
  blocks: Blocks,
  files: Files,
  sheet: Sheet,
  clipboardPen: ClipboardPen,
  dollar: DollarSign,
  clock: Clock,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  plus: Plus
>>>>>>> 8312d78f775457b87697f2a6ebd91d46b2676e01
}
