import { z } from "zod"

export const URGENCY_OPTIONS = [
  { label: "Hot! - Shortage", value: "hot-shortage" },
  { label: "Hot! - Other", value: "hot-other" },
  { label: "Normal - VMI", value: "normal-vmi" },
  { label: "Normal - BOM Scrub", value: "normal-bom-scrub" },
  { label: "Low - Cost Savings", value: "low-cost-savings" },
  { label: "Low - Other", value: "low-other" },
  { label: "Normal", value: "normal" },
  { label: "Purchasing Initiated", value: "purchasing-initiated" },
  { label: "Sales Initiated", value: "sales-initiated" },
]

export const BROKER_BUY_OPTIONS = [
  { label: "Broker Buy", value: "broker-buy" },
  { label: "VMI", value: "VMI" },
  { label: "Pass-Through", value: "pass-through" },
  { label: "Spot Buy", value: "spot-buy" },
  { label: "Not Applicable", value: "not-applicable" },
]

export const PURCHASING_STATUS_OPTIONS = [
  { label: "New", value: "new" },
  { label: "US Sourcing", value: "us-sourcing" },
  { label: "Sourcing", value: "sourcing" },
  { label: "Answers Back", value: "answers-back" },
  { label: "Cont. Sourcing", value: "cont-sourcing" },
  { label: "2nd Round Sourcing", value: "2nd-round-sourcing" },
  { label: "3rd Round Sourcing", value: "3rd-round-sourcing" },
  { label: "Closed", value: "closed" },
  { label: "Master List", value: "master-list" },
]

export const RESULT_OPTIONS = [
  { label: "Not Quoted", value: "not-quoted" },
  { label: "Quoted - Waiting", value: "quoted-waiting" },
  { label: "Need to Re-Quote", value: "need-to-re-quote" },
  { label: "PO Won", value: "PO Won" },
  { label: "No Bid - Value", value: "no-bid-value" },
  { label: "No Bid - NAM", value: "no-bid-nam" },
  { label: "No PO - D/C", value: "no-po-d-c" },
  { label: "No PO - Outbid", value: "no-po-outbid" },
  { label: "No PO - Price", value: "no-po-price" },
  { label: "No PO - Response Time", value: "no-po-response-time" },
  { label: "No PO - LT Contraint", value: "no-po-lt-contraint" },
  { label: "No PO - No Feedback", value: "no-po-no-feedback" },
  { label: "Cancelled", value: "cancelled" },
  { label: "Other", value: "other" },
  { label: "BOM No PO", value: "bom-no-po" },
  { label: "BOM No Bid", value: "bom-no-bid" },
  { label: "Master List", value: "master-list" },
  { label: "Purchasing Initiated", value: "purchasing-initiated" },
  { label: "Purchasing Initated - Closed", value: "purchasing-initated-closed" },
  { label: "Purchasing Initiated-PO Won", value: "purchasing-initiated-po-won" },
  { label: "Purchasing Initiated-Quoted Waiting", value: "purchasing-initiated-quoted-waiting" },
]

export const REASON_OPTIONS = [
  { label: "Won", value: "won" },
  { label: "Lost", value: "lost" },
]

export const REQ_REVIEW_RESULT_OPTIONS = [
  { label: "Need Better Price", value: "need-better-price" },
  { label: "Need Better DC", value: "need-better-dc" },
  { label: "Need Better LT", value: "need-better-lt" },
  { label: "Need more QTY", value: "need-more-qty" },
  { label: "Waiting for Customer Approval", value: "waiting-for-customer-approval" },
  { label: "No Feedback", value: "no-feedback" },
  { label: "To Close", value: "to-close" },
  { label: "Keep Open - Need Quotes", value: "keep-open-need-quotes" },
  { label: "To Re-Quote", value: "to-re-quote" },
]

export const COMMODITY_TYPE_OPTIONS = [
  { label: "Cables, Wires", value: "cables-wires" },
  { label: "Fuses", value: "fuses" },
  { label: "Connectors", value: "connectors" },
  { label: "Motors/Solenoids", value: "motors-solenoids" },
  { label: "Relays", value: "relays" },
  { label: "Switches", value: "switches" },
  { label: "Crystals", value: "crystals" },
  { label: "Oscillators", value: "oscillators" },
  { label: "Diodes", value: "diodes" },
  { label: "Transistors", value: "transistors" },
  { label: "Fans", value: "fans" },
  { label: "Miscellaneous", value: "miscellaneous" },
  { label: "Inductors", value: "inductors" },
  { label: "Controllers", value: "controllers" },
  { label: "Monitors", value: "monitors" },
  { label: "Lighting", value: "lighting" },
  { label: "FPGAs (ICs)", value: "fpg-as-i-cs" },
  { label: "Microcontrollers (ICs)", value: "microcontrollers-i-cs" },
  { label: "Modules", value: "modules" },
  { label: "SSD", value: "ssd" },
  { label: "HDD", value: "hdd" },
  { label: "Memory Card", value: "memory-card" },
  { label: "NAND Flash", value: "nand-flash" },
  { label: "Memory Modules", value: "memory-modules" },
  { label: "Other", value: "other" },
  { label: "NOR Flash", value: "nor-flash" },
  { label: "CPU", value: "cpu" },
  { label: "Sensors", value: "sensors" },
  { label: "Resistors", value: "resistors" },
  { label: "Tools", value: "tools" },
  { label: "Capacitors", value: "capacitors" },
  { label: "Power Module", value: "power-module" },
  { label: "DIMM", value: "dimm" },
  { label: "SDRAM", value: "sdram" },
  { label: "Transceiver", value: "transceiver" },
  { label: "Servers", value: "servers" },
  { label: "IC", value: "ic" },
  { label: "Processors", value: "processors" },
  { label: "MOSFETS", value: "mosfets" },
  { label: "CPLDs (ICs)", value: "cpl-ds-i-cs" },
  { label: "Converter", value: "converter" },
  { label: "FABMTL,STMP,COVER,KENTON RACK MOUNT", value: "fabmtl-stmp-cover-kenton-rack-mount" },
  { label: "PWRSPLY", value: "pwrsply" },
  { label: "Header MicroFit", value: "header-micro-fit" },
  { label: "ASIC,DOPPLER", value: "asic-doppler" },
  { label: "FABMTL STMP COVER", value: "fabmtl-stmp-cover" },
  { label: "Ferrite Bead", value: "ferrite-bead" },
  { label: "Mempory", value: "mempory" },
  { label: "Memory", value: "memory" },
  { label: "Voltage Regulators", value: "voltage-regulators" },
  { label: "Transformer", value: "transformer" },
  { label: "Audio", value: "audio" },
  { label: "GPS", value: "gps" },
  { label: "Battery Protection", value: "battery-protection" },
  { label: "Accelerometer", value: "accelerometer" },
  { label: "Microprocessors", value: "microprocessors" },
  { label: "THERMISTOR", value: "thermistor" },
  { label: "Transmitters", value: "transmitters" },
  { label: "Modem", value: "modem" },
  { label: "Flexural", value: "flexural" },
  { label: "DDR", value: "ddr" },
  { label: "USB CONTROLER", value: "usb-controler" },
  { label: "SFP+ Cage & Conn Stacked 2x4", value: "sfp-cage-conn-stacked-2x4" },
  { label: "Power Edge CONN Right angle", value: "power-edge-conn-right-angle" },
  { label: "IC TEMPETURE", value: "ic-tempeture" },
  { label: "Battery", value: "battery" },
  { label: "PUSHBUTTON SWITCH RT ANGLE", value: "pushbutton-switch-rt-angle" },
  { label: "DC-DC", value: "dc-dc" },
  { label: "Passive", value: "passive" },
  { label: "TERMINAL", value: "terminal" },
  { label: "Wifi Module", value: "wifi-module" },
  { label: "BLUETOOTH", value: "bluetooth" },
  { label: "Drives and Storage", value: "drives-and-storage" },
  { label: "Camera", value: "camera" },
  { label: "hard drive", value: "hard-drive" },
  { label: "logic cell", value: "logic-cell" },
  { label: "CAP", value: "cap" },
  { label: "OSCILATOR", value: "oscilator" },
  { label: "CONNECTOR", value: "connector" },
  { label: "Varistor Circuit", value: "varistor-circuit" },
  { label: "Fuse Holder", value: "fuse-holder" },
  { label: "Header", value: "header" },
  { label: "Semiconductor", value: "semiconductor" },
  { label: "Memory Devices", value: "memory-devices" },
  { label: "MOSFET", value: "mosfet" },
  { label: "Thyristors", value: "thyristors" },
  { label: "INTERFACE CONTROLLER", value: "interface-controller" },
  { label: "Adapters", value: "adapters" },
  { label: "Power Converter", value: "power-converter" },
  { label: "Regulator", value: "regulator" },
  { label: "RFID", value: "rfid" },
  { label: "Display", value: "display" },
  { label: "Oscillator", value: "oscillator" },
  { label: "Motor Driver", value: "motor-driver" },
  { label: "Power Supply component", value: "power-supply-component" },
  { label: "Fuel Gauge", value: "fuel-gauge" },
  { label: "Power Supply", value: "power-supply" },
  { label: "PCLe", value: "pc-le" },
  { label: "Mainboard", value: "mainboard" },
  { label: "Heatspreader", value: "heatspreader" },
  { label: "res", value: "res" },
  { label: "Amplifier", value: "amplifier" },
  { label: "FPGA (ICs)", value: "fpga-i-cs" },
  { label: "Isolators", value: "isolators" },
  { label: "RF Multiplexer", value: "rf-multiplexer" },
  { label: "CHIPSET", value: "chipset" },
  { label: "MOTOR DRIVE", value: "motor-drive" },
  { label: "Diode", value: "diode" },
  { label: "Ethernet Controller", value: "ethernet-controller" },
  { label: "Bluetooth Module", value: "bluetooth-module" },
  { label: "Clock Generators", value: "clock-generators" },
  { label: "TERFACE CONTROLLER", value: "terface-controller" },
  { label: "Inductor", value: "inductor" },
  { label: "Inductor ", value: "inductor" },
  { label: "MICROPROCESSOR", value: "microprocessor" },
  { label: "BUFFER", value: "buffer" },
  { label: "SWITCH", value: "switch" },
  { label: "bnavarrete@omegagti.com", value: "bnavarrete-omegagti-com" },
  { label: "Varistor Circuits", value: "varistor-circuits" },
  { label: "Pressure Sensor", value: "pressure-sensor" },
  { label: "USB_HUB", value: "usb-hub" },
  { label: "CHIP RESISTOR", value: "chip-resistor" },
  { label: "LDO VOLTAGE REGULATOR", value: "ldo-voltage-regulator" },
  { label: "FLUX", value: "flux" },
  { label: "CHIP", value: "chip" },
  { label: "BAND", value: "band" },
  { label: "SENSOR", value: "sensor" },
  { label: "DECODER", value: "decoder" },
  { label: "FLASH", value: "flash" },
  { label: "POWER-LINE", value: "power-line" },
  { label: "IC MPO", value: "ic-mpo" },
  { label: "Laser", value: "laser" },
  { label: "Filter", value: "filter" },
  { label: "Power Cord", value: "power-cord" },
  { label: "MLCC", value: "mlcc" },
  { label: "Led", value: "led" },
  { label: "epld", value: "epld" },
  { label: "crystal", value: "crystal" },
  { label: "LP", value: "lp" },
  { label: "CMOS Auto", value: "cmos-auto" },
  { label: "Ethernet Connector", value: "ethernet-connector" },
  { label: "CAPACITOR", value: "capacitor" },
  { label: "RECTIFIER", value: "rectifier" },
  { label: "C MPU I.MX6DP ENHAN 624FCBGA", value: "c-mpu-i-mx6-dp-enhan-624-fcbga" },
  { label: "SOC i.MX 6Solo ARM", value: "soc-i-mx-6-solo-arm" },
  { label: "IC MCU", value: "ic-mcu" },
  { label: "High speed CAN", value: "high-speed-can" },
  { label: "PMB", value: "pmb" },
  { label: "WIRELESS MOD", value: "wireless-mod" },
  { label: "MCU", value: "mcu" },
  { label: "NIC", value: "nic" },
  { label: "ESD", value: "esd" },
  { label: "Drivers", value: "drivers" },
  { label: "Conductors", value: "conductors" },
  { label: "FERRITE", value: "ferrite" },
  { label: "Op Amp Quad", value: "op-amp-quad" },
  { label: "OPTICAL", value: "optical" },
  { label: "LCD SCREEN", value: "lcd-screen" },
  { label: "clock", value: "clock" },
  { label: "conv", value: "conv" },
  { label: "RF Front End", value: "rf-front-end" },
  { label: "Diod", value: "diod" },
  { label: "Trans", value: "trans" },
  { label: "Memoria flash", value: "memoria-flash" },
  { label: "Conectores ", value: "conectores" },
  { label: "RESISTEN", value: "resisten" },
  { label: "Quartz", value: "quartz" },
  { label: "MOSFET P-CH 20V 1.6A SUPERSOT3", value: "mosfet-p-ch-20-v-1-6-a-supersot3" },
  { label: "IC MCU 16BIT 128KB FLASH 64VQFN", value: "ic-mcu-16-bit-128-kb-flash-64-vqfn" },
  { label: " ISOLATOR", value: "isolator" },
  { label: "Microcontroller", value: "microcontroller" },
  { label: "Power Supply Module", value: "power-supply-module" },
  { label: "Transistor", value: "transistor" },
  { label: "Choke", value: "choke" },
  { label: "Barcode Label", value: "barcode-label" },
  { label: "IC MCU 32BIT 512KB FLASH 100LQFP", value: "ic-mcu-32-bit-512-kb-flash-100-lqfp" },
  { label: "Enclosure", value: "enclosure" },
  { label: "IC FLASH 32GBIT MMC 100LBGA", value: "ic-flash-32-gbit-mmc-100-lbga" },
  { label: "Controller", value: "controller" },
  { label: "IC REG LINEAR 3.3V 150MA 8QFN", value: "ic-reg-linear-3-3-v-150-ma-8-qfn" },
  { label: "LGA2011-3 Socket", value: "lga2011-3-socket" },
  { label: "IC RF TXRX+MCU 802.15.4 73VFQFN", value: "ic-rf-txrx-mcu-802-15-4-73-vfqfn" },
  { label: "BOARD IC", value: "board-ic" },
  { label: "CCG6SF 48-QFN", value: "ccg6-sf-48-qfn" },
  { label: "MAC", value: "mac" },
  { label: "Module", value: "module" },
  { label: "IC-FEPROM-M", value: "ic-feprom-m" },
  { label: "IC-MP MIPS 800MHZ FCBGA900 CN6230 4-CORE PB FREE", value: "ic-mp-mips-800-mhz-fcbga900-cn6230-4-core-pb-free" },
  { label: "IC-FEPROM-D", value: "ic-feprom-d" },
  { label: "IC 16BIT", value: "ic-16-bit" },
  { label: "IC 900MHZ", value: "ic-900-mhz" },
  { label: "IC-REG-LDO-SOT-23-8PIN", value: "ic-reg-ldo-sot-23-8-pin" },
  { label: "IC, Si4063-B1B-FM, TRANSCEIVER", value: "ic-si4063-b1-b-fm-transceiver" },
  { label: "IC RF TXRX ISM 20VFQFN", value: "ic-rf-txrx-ism-20-vfqfn" },
  { label: "AXIOM 16GBASE-SW SFP+ TRANSCEIVER", value: "axiom-16-gbase-sw-sfp-transceiver" },
  { label: "Deserializer", value: "deserializer" },
  { label: "RECEIVER", value: "receiver" },
  { label: "Stereo Audio DAC 192ksps 24bit 32-Pin VQFN EP T/R", value: "stereo-audio-dac-192ksps-24bit-32-pin-vqfn-ep-t-r" },
  { label: "CAP, 4700PF, 2 KV, 10%, X7R, 1808", value: "cap-4700-pf-2-kv-10-x7-r-1808" },
  { label: "AMP", value: "amp" },
  { label: "CONCEALED", value: "concealed" },
  { label: "MPU i.MX RISC 32-Bit 1", value: "mpu-i-mx-risc-32-bit-1" },
  { label: "power switch", value: "power-switch" },
  { label: "MCU 32-bit ARM Cortex", value: "mcu-32-bit-arm-cortex" },
  { label: 'LABEL 0.5"H X 2"W WHT 1=3000PCS', value: "label-0-5-h-x-2-w-wht-1-3000-pcs" },
  { label: "RF Transformer 1", value: "rf-transformer-1" },
  { label: "RF TX IC 142MHZ-", value: "rf-tx-ic-142-mhz" },
  { label: "MCU 16-bit", value: "mcu-16-bit" },
  { label: "Resistor", value: "resistor" },
  { label: "Chipset Platform", value: "chipset-platform" },
  { label: "Full Speed/High Speed Multi Format SD/MMC", value: "full-speed-high-speed-multi-format-sd-mmc" },
  { label: "WLAN+BTCombo Module IEEE 802.", value: "wlan-bt-combo-module-ieee-802" },
  { label: "IC DRAM 4GBIT PARALLEL 78FBGA", value: "ic-dram-4-gbit-parallel-78-fbga" },
  { label: "SOC i.MX 6Dual ARM", value: "soc-i-mx-6-dual-arm" },
  { label: "DUAL-CHANNEL 10-GBE SFI-TO-XAUI", value: "dual-channel-10-gbe-sfi-to-xaui" },
  { label: "MotionTracking Device Digital", value: "motion-tracking-device-digital" },
  { label: "V-Ref Precision", value: "v-ref-precision" },
  { label: "Power Relay", value: "power-relay" },
  { label: "RAM MODULE", value: "ram-module" },
  { label: "N/A", value: "n-a" },
  { label: "CAN 1Mbps Standby", value: "can-1-mbps-standby" },
  { label: "SATA", value: "sata" },
  { label: "IC CPLD 72MC", value: "ic-cpld-72-mc" },
  { label: "ENCODER", value: "encoder" },
  { label: "CPLD", value: "cpld" },
  { label: "IC SUPERVISOR 10 CHANNEL", value: "ic-supervisor-10-channel" },
  { label: "Osc", value: "osc" },
  { label: "Fuse", value: "fuse" },
  { label: "Conn", value: "conn" },
  { label: "Magnetic Hydraulic Circuit Breaker", value: "magnetic-hydraulic-circuit-breaker" },
  { label: "RJ45", value: "rj45" },
  { label: "IC FLASH", value: "ic-flash" },
  { label: "Battery Management", value: "battery-management" },
  { label: "CMD", value: "cmd" },
  { label: "IC HOTSWAP", value: "ic-hotswap" },
  { label: "IC Motor Driver", value: "ic-motor-driver" },
  { label: "SENSOR OPTO TRANS 1MM SMD", value: "sensor-opto-trans-1-mm-smd" },
  { label: "Trans Darlington", value: "trans-darlington" },
  { label: "IC SUPERVISOR", value: "ic-supervisor" },
  { label: "RES 32K", value: "res-32-k" },
  { label: "CAN 1Mbps", value: "can-1-mbps" },
  { label: "TVS Diode Single", value: "tvs-diode-single" },
  { label: "TVS Diode Single Uni-Dir", value: "tvs-diode-single-uni-dir" },
  { label: "ESD Suppressor DIO", value: "esd-suppressor-dio" },
  { label: "Network Interface Card", value: "network-interface-card" },
  { label: "PTC Resettable Fus", value: "ptc-resettable-fus" },
  { label: "SICFET N-CH", value: "sicfet-n-ch" },
  { label: "IC OPAMP ISOLATION", value: "ic-opamp-isolation" },
  { label: "IC MULTIPLEXER", value: "ic-multiplexer" },
  { label: "Automotive Single-", value: "automotive-single" },
  { label: "IC LED CONTROLLER", value: "ic-led-controller" },
  { label: "Digital Isolator", value: "digital-isolator" },
  { label: "CONN SUCKET", value: "conn-sucket" },
  { label: "Conn Housing PL 2 P", value: "conn-housing-pl-2-p" },
  { label: "H-Bridge Motor", value: "h-bridge-motor" },
  { label: "Single Transmitter", value: "single-transmitter" },
  { label: "DRAM", value: "dram" },
  { label: "TPASY;MEGARAID 12G PCI-E", value: "tpasy-megaraid-12-g-pci-e" },
  { label: "IC-MP,X86,64BIT,2.5 GHz,", value: "ic-mp-x86-64-bit-2-5-g-hz" },
  { label: "INTEL XEON", value: "intel-xeon" },
  { label: "OPAMP Dual", value: "opamp-dual" },
  { label: "IC MPU", value: "ic-mpu" },
  { label: "IC Driver Gate", value: "ic-driver-gate" },
  { label: "VGA PORT", value: "vga-port" },
  { label: "IC OPAMP GP", value: "ic-opamp-gp" },
  { label: "OP AMP Single", value: "op-amp-single" },
  { label: "Power Load Switch", value: "power-load-switch" },
  { label: "ETHERNET TRANSCEIVER", value: "ethernet-transceiver" },
  { label: "bus switch", value: "bus-switch" },
  { label: "IC CPLD", value: "ic-cpld" },
  { label: "I2C Bus", value: "i2-c-bus" },
  { label: "FCBGA", value: "fcbga" },
  { label: "IC RECEIVER", value: "ic-receiver" },
  { label: "IC PWR SWITCH", value: "ic-pwr-switch" },
  { label: "IC REG", value: "ic-reg" },
  { label: "IC RF Switch", value: "ic-rf-switch" },
  { label: "IC Translator", value: "ic-translator" },
  { label: "IC Clock Buffer", value: "ic-clock-buffer" },
  { label: "IC Real Time Clock", value: "ic-real-time-clock" },
  { label: "RES Thick Film", value: "res-thick-film" },
  { label: "ASIX ELECTRONICS", value: "asix-electronics" },
  { label: "I2C SWITCH W/ RESET", value: "i2-c-switch-w-reset" },
  { label: "Temperature Sensor", value: "temperature-sensor" },
  { label: "IC TXRX NON-INVERT", value: "ic-txrx-non-invert" },
  { label: "IC PCIE BUFFER", value: "ic-pcie-buffer" },
  { label: "DIGITAL SENSOR", value: "digital-sensor" },
  { label: "CPLD MAX® V", value: "cpld-max-v" },
  { label: "IC ADC", value: "ic-adc" },
  { label: "Fitting", value: "fitting" },
  { label: "USB Power Switch", value: "usb-power-switch" },
  { label: "IC TRNSLTR BIDIRECTIONAL", value: "ic-trnsltr-bidirectional" },
  { label: "PCI Express", value: "pci-express" },
  { label: "Conn Shrouded Header", value: "conn-shrouded-header" },
  { label: "Clock Fanout Buffer", value: "clock-fanout-buffer" },
  { label: "IC EEPROM", value: "ic-eeprom" },
  { label: "Fuse Limiter", value: "fuse-limiter" },
  { label: "OR Controller", value: "or-controller" },
  { label: "Diode Schottky", value: "diode-schottky" },
  { label: "Power inductor", value: "power-inductor" },
  { label: "Modular Connectors / Ethernet Connectors", value: "modular-connectors-ethernet-connectors" },
  { label: "MPU", value: "mpu" },
  { label: "IC Clock", value: "ic-clock" },
  { label: "Mechanical Module Dust Cap", value: "mechanical-module-dust-cap" },
  { label: "Voltage Level Translator", value: "voltage-level-translator" },
  { label: "IC Telecom", value: "ic-telecom" },
  { label: "IC Current Monitor", value: "ic-current-monitor" },
  { label: "TTL Oscillator", value: "ttl-oscillator" },
  { label: "Res Thin Film", value: "res-thin-film" },
  { label: "IC VREF", value: "ic-vref" },
  { label: "Telecom Transformer", value: "telecom-transformer" },
  { label: "Conn Unshrouded Header", value: "conn-unshrouded-header" },
  { label: "IC PROM", value: "ic-prom" },
  { label: "Ceramic RES", value: "ceramic-res" },
  { label: "Rectifier Diode Schottky", value: "rectifier-diode-schottky" },
  { label: "SCHOTTKY DIODE", value: "schottky-diode" },
  { label: "Alternistor", value: "alternistor" },
  { label: "Headers & Wire Housings", value: "headers-wire-housings" },
  { label: "Module DC-DC", value: "module-dc-dc" },
  { label: "Hot Swap Controller", value: "hot-swap-controller" },
  { label: "SATA Plug", value: "sata-plug" },
  { label: "Ethernet DC", value: "ethernet-dc" },
  { label: "IC TRNSLTR UNIDIRECTIONAL", value: "ic-trnsltr-unidirectional" },
  { label: "Conn RJ-45 F", value: "conn-rj-45-f" },
  { label: "I/O Connectors SATA", value: "i-o-connectors-sata" },
  { label: "Power Management IC 56-Pin QFN EP T/R", value: "power-management-ic-56-pin-qfn-ep-t-r" },
  { label: "IC TLE5012B ANGLE SNSR SOIC8", value: "ic-tle5012-b-angle-snsr-soic8" },
  { label: "IC CONTROL", value: "ic-control" },
  { label: "Processor Supervisor", value: "processor-supervisor" },
  { label: "IC PWR MGMT", value: "ic-pwr-mgmt" },
  { label: "IC I/O EXPANDER I2C", value: "ic-i-o-expander-i2-c" },
  { label: "ASIC,WOODSIDE PR02,SLC1152,STDCELL", value: "asic-woodside-pr02-slc1152-stdcell" },
  { label: "TRANS NPN", value: "trans-npn" },
  { label: "Circuit Breaker", value: "circuit-breaker" },
  { label: "Comparator IC", value: "comparator-ic" },
  { label: "FUSE BOARD MOUNT", value: "fuse-board-mount" },
  { label: "ACCEL 2-16G I2C/SPI 1", value: "accel-2-16-g-i2-c-spi-1" },
  { label: "32-bit MCU, Power Arch cores", value: "32-bit-mcu-power-arch-cores" },
  { label: "IC DRAM", value: "ic-dram" },
  { label: "Common Mode Chokes", value: "common-mode-chokes" },
  { label: "POWER SEQUENCER", value: "power-sequencer" },
  { label: "SRAM Chip Sync Dual", value: "sram-chip-sync-dual" },
  { label: "IC Backup Controller", value: "ic-backup-controller" },
  { label: "RES SMD", value: "res-smd" },
  { label: "RX TXRX", value: "rx-txrx" },
  { label: "IC AND Gate", value: "ic-and-gate" },
  { label: "Receptacle", value: "receptacle" },
  { label: "Surface Mount Nuts", value: "surface-mount-nuts" },
  { label: "SLC NAND Flash Parallel", value: "slc-nand-flash-parallel" },
  { label: "Triple Transmitter", value: "triple-transmitter" },
  { label: "High Frequency Synchronous Power Module", value: "high-frequency-synchronous-power-module" },
  { label: "SAW Filter", value: "saw-filter" },
  { label: "Spread Spectrum Clock G", value: "spread-spectrum-clock-g" },
  { label: "OPTOCOUPLER", value: "optocoupler" },
  { label: "FAN 12V DC 1A 15300RPM 30.5", value: "fan-12-v-dc-1-a-15300-rpm-30-5" },
  { label: "IC Inverter", value: "ic-inverter" },
  { label: "FILM CA", value: "film-ca" },
  { label: "VL CON", value: "vl-con" },
  { label: "Conn Micro High Speed Socket Strip", value: "conn-micro-high-speed-socket-strip" },
  { label: "Reneral Purpose Relays", value: "reneral-purpose-relays" },
  { label: "FPGA", value: "fpga" },
  { label: "IC HOT SWAP", value: "ic-hot-swap" },
  { label: "ESD DIODE", value: "esd-diode" },
  { label: "IC OP AMP Single", value: "ic-op-amp-single" },
  { label: "TVS Diodes", value: "tvs-diodes" },
  { label: "TVS DIODE", value: "tvs-diode" },
  { label: "AND Gate", value: "and-gate" },
  { label: "NOR Flash Parallel", value: "nor-flash-parallel" },
  { label: "Ferrite Beads Multi-Layer", value: "ferrite-beads-multi-layer" },
  { label: "D/C to D/C", value: "d-c-to-d-c" },
  { label: "Comparator", value: "comparator" },
  { label: "LED Driver", value: "led-driver" },
  { label: "LDO", value: "ldo" },
  { label: "Trans 2PNP", value: "trans-2-pnp" },
  { label: "IC DUAL DIFF COMPARATOR", value: "ic-dual-diff-comparator" },
  { label: "IC REG BUCK", value: "ic-reg-buck" },
  { label: "LDO Voltage Regulators", value: "ldo-voltage-regulators" },
  { label: "Ethernet Physical Layer", value: "ethernet-physical-layer" },
  { label: "DC to DC", value: "dc-to-dc" },
  { label: "HOT-SWAP CONTROLLER", value: "hot-swap-controller" },
  { label: "8-Channel Hex ADC Delta-Sigma", value: "8-channel-hex-adc-delta-sigma" },
  { label: "MOS", value: "mos" },
  { label: "NTC THERMISTOR", value: "ntc-thermistor" },
  { label: "DC COMMON MODE", value: "dc-common-mode" },
  { label: "Digital Vacuum Sensor", value: "digital-vacuum-sensor" },
  { label: "160X160 CROSSPOINT SWITCH 12.5GB", value: "160-x160-crosspoint-switch-12-5-gb" },
  { label: "Circuit Board Indicator", value: "circuit-board-indicator" },
  { label: "OPTOISO 5KV 1CH", value: "optoiso-5-kv-1-ch" },
  { label: "OPTOISOLTR 5K", value: "optoisoltr-5-k" },
  { label: "IC ETHERNET S", value: "ic-ethernet-s" },
  { label: "QuickSwitch Products 3", value: "quick-switch-products-3" },
  { label: "IC Buffer Non-invert", value: "ic-buffer-non-invert" },
  { label: "IC Voltage Reference", value: "ic-voltage-reference" },
  { label: "IC Physical Layer", value: "ic-physical-layer" },
  { label: "Universal Frequency Translator", value: "universal-frequency-translator" },
  { label: "Thermistor, Coated In Header", value: "thermistor-coated-in-header" },
  { label: "Embedded Modem", value: "embedded-modem" },
  { label: "Analog Switch", value: "analog-switch" },
  { label: "88E6240-A1-TFJ2I000", value: "88-e6240-a1-tfj2-i000" },
  { label: "4A CONTINUOUS CURRENT, SUPPORTS LOADS 6A", value: "4-a-continuous-current-supports-loads-6-a" },
  { label: "OPAMP 20MHZ CMOS SOT23-5", value: "opamp-20-mhz-cmos-sot23-5" },
  { label: "ANALOG CMOS MULTIPLEXER 1X16:1 TSSOP-28", value: "analog-cmos-multiplexer-1-x16-1-tssop-28" },
  { label: "CAP-SM CASE X,FP 470UF,6.3V 20% TA TLRNC", value: "cap-sm-case-x-fp-470-uf-6-3-v-20-ta-tlrnc" },
  { label: "MOSFET60VDS,100 AID,1.45 MOHMRDS,TDSON8", value: "mosfet60-vds-100-aid-1-45-mohmrds-tdson8" },
  { label: "12-BIT ADC 12 12-BIT DACS HTQFP-64-EP", value: "12-bit-adc-12-12-bit-dacs-htqfp-64-ep" },
  { label: "4 MB SERIAL (SPI) F-RAM DFN-8", value: "4-mb-serial-spi-f-ram-dfn-8" },
  { label: "ULTRALOW-PWR150MA DO 3.3V WT SOT-23-5", value: "ultralow-pwr150-ma-do-3-3-v-wt-sot-23-5" },
  { label: "Real Time Clock IC", value: "real-time-clock-ic" },
  { label: "SMIC,Flash Serial 8MB", value: "smic-flash-serial-8-mb" },
  { label: "CONN,PLUG, 2p, 5mm 16A", value: "conn-plug-2p-5mm-16-a" },
  { label: "IC INTFACE SPECIALIZED", value: "ic-intface-specialized" },
  { label: "Conv DC-DC 4.5V", value: "conv-dc-dc-4-5-v" },
  { label: "IC SMD MCU 32BIT 512KB FLASH 64LQFP C", value: "ic-smd-mcu-32-bit-512-kb-flash-64-lqfp-c" },
  { label: "CAP ALUM POLY HYB", value: "cap-alum-poly-hyb" },
  { label: "Rectifier Diode Switching 600V 4A 75ns 2-Pin", value: "rectifier-diode-switching-600-v-4-a-75ns-2-pin" },
  { label: "DIST Single", value: "dist-single" },
  { label: "Full Speed/High Speed", value: "full-speed-high-speed" },
  { label: "Inverter", value: "inverter" },
  { label: "Sleeving", value: "sleeving" },
  { label: "2-CHANNEL ANALOG INPUT", value: "2-channel-analog-input" },
  { label: "Output Module", value: "output-module" },
  { label: "SMVector", value: "sm-vector" },
  { label: "Manager, Distribution", value: "manager-distribution" },
  { label: "Procurement Administrator", value: "procurement-administrator" },
  { label: "Manager, Procurement Integration", value: "manager-procurement-integration" },
  { label: "Director, Corporate Purchasing", value: "director-corporate-purchasing" },
  { label: "Procurement & Facilities Head", value: "procurement-facilities-head" },
  { label: "AC/DC Converter", value: "ac-dc-converter" },
  { label: "Conn Terminal Block F", value: "conn-terminal-block-f" },
  { label: "Graphic Panel", value: "graphic-panel" },
  { label: "Wireless Card", value: "wireless-card" },
  { label: "10G MULTI LAYER SWITCH", value: "10-g-multi-layer-switch" },
  { label: "720G 10GBE/40GBE/", value: "720-g-10-gbe-40-gbe" },
  { label: "BGA", value: "bga" },
  { label: "NETGEAR M4300-52G-POE+ - SWITCH", value: "netgear-m4300-52-g-poe-switch" },
  { label: "Safety Capacitor", value: "safety-capacitor" },
  { label: "Safety Industrial Relay", value: "safety-industrial-relay" },
  { label: "AC Gearmotor", value: "ac-gearmotor" },
  { label: "SAS9305-16E SINGLE KIT NA A 00 L", value: "sas9305-16-e-single-kit-na-a-00-l" },
  { label: "IC Linear Comparators", value: "ic-linear-comparators" },
  { label: "Drain Valve", value: "drain-valve" },
  { label: "Thermal Pads", value: "thermal-pads" },
  { label: "IC Memory", value: "ic-memory" },
  { label: "AC SWITCHING CONTROLLER", value: "ac-switching-controller" },
  { label: "Hi Side Dual", value: "hi-side-dual" },
  { label: "Crystal Osillator", value: "crystal-osillator" },
  { label: "Breaker", value: "breaker" },
  { label: "Contactor", value: "contactor" },
  { label: "System Board", value: "system-board" },
  { label: "EEPROM", value: "eeprom" },
  { label: "Assembly", value: "assembly" },
  { label: "Quarzoszillator", value: "quarzoszillator" },
  { label: "Embedded Solutions", value: "embedded-solutions" },
  { label: "Circuit Board", value: "circuit-board" },
  { label: "ADC", value: "adc" },
  { label: "DGT ISOL", value: "dgt-isol" },
  { label: "Voltage Regulator", value: "voltage-regulator" },
  { label: "Op Amp", value: "op-amp" },
  { label: "OpAmp Quad", value: "op-amp-quad" },
  { label: "Op Amp Dual", value: "op-amp-dual" },
  { label: "IC  INTFACE SPECIALIZED", value: "ic-intface-specialized" },
  { label: "eMMC", value: "e-mmc" },
  { label: "Wireless Connectivity IC", value: "wireless-connectivity-ic" },
  { label: "DC DC", value: "dc-dc" },
  { label: "IC PWR DRIVER", value: "ic-pwr-driver" },
  { label: "IC Hall SW BiPolar", value: "ic-hall-sw-bi-polar" },
  { label: "CMC", value: "cmc" },
  { label: "Ethernet Network Adapter", value: "ethernet-network-adapter" },
  { label: "Raspberry Pi 3 B+", value: "raspberry-pi-3-b" },
  { label: "Multiplexer/Demultiplexer Bus Switch", value: "multiplexer-demultiplexer-bus-switch" },
  { label: "Buck-Boost Switching Regulator", value: "buck-boost-switching-regulator" },
  { label: "Super Capacitor", value: "super-capacitor" },
  { label: "Potentiometer", value: "potentiometer" },
  { label: "I2C Interface", value: "i2-c-interface" },
  { label: "USB Controller", value: "usb-controller" },
  { label: "LVDS Buffer", value: "lvds-buffer" },
  { label: "Integrated buck gate driver", value: "integrated-buck-gate-driver" },
  { label: "Single GBE Serdes", value: "single-gbe-serdes" },
  { label: "Voltage monitor", value: "voltage-monitor" },
  { label: "FANOUT BUFFER", value: "fanout-buffer" },
  { label: "Switching Battery Charger", value: "switching-battery-charger" },
  { label: "USB-to-UART", value: "usb-to-uart" },
  { label: "INST Amp", value: "inst-amp" },
  { label: "Swap Controller", value: "swap-controller" },
  { label: "IC BATT", value: "ic-batt" },
  { label: "WIRELESS POWER RECEIVER", value: "wireless-power-receiver" },
  { label: "EMI Filter", value: "emi-filter" },
  { label: "RF SYNTHESIZER", value: "rf-synthesizer" },
  { label: "FPGA PolarFire Family", value: "fpga-polar-fire-family" },
  { label: "FPGA SmartFusion", value: "fpga-smart-fusion" },
  { label: "IC ADC DRIVER", value: "ic-adc-driver" },
  { label: "DAC 4-CH Resistor-String", value: "dac-4-ch-resistor-string" },
  { label: "Video Decoder", value: "video-decoder" },
  { label: "USB Type-C Controller", value: "usb-type-c-controller" },
  { label: "Optoelectronics", value: "optoelectronics" },
  { label: "16 Channel Single ADC", value: "16-channel-single-adc" },
  { label: "Schmitt Trigger Buffer", value: "schmitt-trigger-buffer" },
  { label: "Ethernet Switch", value: "ethernet-switch" },
  { label: "Switching Voltage Reg", value: "switching-voltage-reg" },
  { label: "Cellular Modules", value: "cellular-modules" },
  { label: "Switching Voltage Regulators", value: "switching-voltage-regulators" },
  { label: "DDR5 32GB 2Rx8", value: "ddr5-32-gb-2-rx8" },
  { label: "Linear Regulator IC", value: "linear-regulator-ic" },
  { label: "Diode Module", value: "diode-module" },
  { label: "Amplifier circuit", value: "amplifier-circuit" },
  { label: "Display Drivers", value: "display-drivers" },
  { label: "IC TRANSCEIVER", value: "ic-transceiver" },
  { label: "Network Adapter", value: "network-adapter" },
  { label: "Analog Multiplexer Single", value: "analog-multiplexer-single" },
  { label: "$249.00", value: "249-00" },
  { label: "5.949", value: "5-949" },
  { label: "23.4", value: "23-4" },
  { label: "35.91", value: "35-91" },
  { label: "12.3", value: "12-3" },
  { label: "$198.60", value: "198-60" },
  { label: "6.8", value: "6-8" },
  { label: "10.3", value: "10-3" },
  { label: "19.4", value: "19-4" },
  { label: "1.34", value: "1-34" },
  { label: "39.6", value: "39-6" },
  { label: "32.13", value: "32-13" },
  { label: "9.86", value: "9-86" },
  { label: "PTC Resettable Fuse", value: "ptc-resettable-fuse" },
  { label: "Varistor", value: "varistor" },
  { label: "Pwr Mux Autoswitch", value: "pwr-mux-autoswitch" },
  { label: "Embedded Board", value: "embedded-board" },
  { label: "2-Input AND Logic Gate", value: "2-input-and-logic-gate" },
  { label: "Thermocouple", value: "thermocouple" },
  { label: "Thermocouple Wires", value: "thermocouple-wires" },
  { label: "Spacer Mount", value: "spacer-mount" },
  { label: "Circuit Protection", value: "circuit-protection" },
  { label: "Test Probe", value: "test-probe" },
  { label: "IC RTC CLK", value: "ic-rtc-clk" },
  { label: "IFX POWERSTAGE", value: "ifx-powerstage" },
  { label: "IC FPGA", value: "ic-fpga" },
  { label: "Digital Potentiometer", value: "digital-potentiometer" },
  { label: "Single Port  10G", value: "single-port-10-g" },
  { label: "Fiber Optic Transmitters", value: "fiber-optic-transmitters" },
  { label: "DC/DC Converter", value: "dc-dc-converter" },
  { label: "RF/IF", value: "rf-if" },
  { label: "Spade Perma-Seal", value: "spade-perma-seal" },
  { label: "Nand Gate", value: "nand-gate" },
  { label: "Optoisolator", value: "optoisolator" },
  { label: "Supervisory Circuits", value: "supervisory-circuits" },
  { label: "battery monitor", value: "battery-monitor" },
  { label: "IC RMS", value: "ic-rms" },
  { label: "Gate Drivers", value: "gate-drivers" },
  { label: "Ethernet Module", value: "ethernet-module" },
  { label: "Sockets", value: "sockets" },
  { label: "QSFP28 CAGE", value: "qsfp28-cage" },
  { label: "IC MCD CCG5C WIRED 40-QFN", value: "ic-mcd-ccg5-c-wired-40-qfn" },
  { label: "TRANS PNP 40V 0.2A", value: "trans-pnp-40-v-0-2-a" },
  { label: "IC CURRENT SENSE 1", value: "ic-current-sense-1" },
  { label: "LOW COST CURRENT SENSOR WITH COM", value: "low-cost-current-sensor-with-com" },
  { label: "Switch Integrated Buck-Boost Converte", value: "switch-integrated-buck-boost-converte" },
  { label: "HBA Card", value: "hba-card" },
  { label: "Fixed Inductors", value: "fixed-inductors" },
  { label: "USB Transceiver", value: "usb-transceiver" },
  { label: "non ins fem dscn", value: "non-ins-fem-dscn" },
  { label: "LIN controller", value: "lin-controller" },
  { label: "Dual Transmitter rcvr", value: "dual-transmitter-rcvr" },
  { label: "Working", value: "working" },
  { label: "Translator", value: "translator" },
  { label: "Relay", value: "relay" },
  { label: "Thermal Interface", value: "thermal-interface" },
  { label: "SWORDFISH", value: "swordfish" },
  { label: "buck regulator", value: "buck-regulator" },
  { label: "IC Audio Amplifier", value: "ic-audio-amplifier" },
  { label: "IC UART", value: "ic-uart" },
  { label: "ICs", value: "i-cs" },
  { label: "SOT ESD PROTECTION DEVICE", value: "sot-esd-protection-device" },
  { label: "Serial 15 Gbps Octal", value: "serial-15-gbps-octal" },
  { label: "Clock Buffer", value: "clock-buffer" },
  { label: "CABLE", value: "cable" },
  { label: "Ferrite Beads", value: "ferrite-beads" },
  { label: "Isolator", value: "isolator" },
  { label: "SOT", value: "sot" },
  { label: "Fasteners", value: "fasteners" },
  { label: "Transformers", value: "transformers" },
  { label: "Regulators", value: "regulators" },
  { label: "IC-Logic", value: "ic-logic" },
  { label: "Miscellaneouos", value: "miscellaneouos" },
  { label: "DAC", value: "dac" },
  { label: "TLE9251LEXUMA1", value: "tle9251-lexuma1" },
  { label: "Terminal Block", value: "terminal-block" },
  { label: "Crystal Oscillators", value: "crystal-oscillators" },
  { label: "Filters", value: "filters" },
  { label: "Power Modules", value: "power-modules" },
  { label: "DC/DC converters", value: "dc-dc-converters" },
  { label: "Amplifiers", value: "amplifiers" },
  { label: "TRIAC Alternistor", value: "triac-alternistor" },
  { label: "AC/DC Power Supply", value: "ac-dc-power-supply" },
  { label: "Microcontroller (ICs)", value: "microcontroller-i-cs" },
  { label: "Signal Switch", value: "signal-switch" },
  { label: "Battery Charger Controller", value: "battery-charger-controller" },
  { label: "IMU", value: "imu" },
  { label: "Comparator Quad", value: "comparator-quad" },
  { label: "RJ45 Patch Cord", value: "rj45-patch-cord" },
  { label: "VIDEO AMPLIFIER", value: "video-amplifier" },
  { label: "Voltage Supervisors", value: "voltage-supervisors" },
  { label: "piezo alarm", value: "piezo-alarm" },
  { label: "Pushbutton Switches", value: "pushbutton-switches" },
  { label: "Multivibrator", value: "multivibrator" },
  { label: "Analog Converters", value: "analog-converters" },
  { label: "Converters", value: "converters" },
  { label: "$300.00", value: "300-00" },
  { label: "$25.00", value: "25-00" },
  { label: "$20.00", value: "20-00" },
  { label: "$200.00", value: "200-00" },
  { label: "$23.00", value: "23-00" },
  { label: "$25", value: "25" },
  { label: "$140.00", value: "140-00" },
  { label: "$5.00", value: "5-00" },
  { label: "$35", value: "35" },
  { label: "$40.00", value: "40-00" },
  { label: "$0.90", value: "0-90" },
  { label: "$3.00", value: "3-00" },
  { label: "$95.00", value: "95-00" },
  { label: "$30.00", value: "30-00" },
  { label: "$85.00", value: "85-00" },
  { label: "$85", value: "85" },
  { label: "$3.34", value: "3-34" },
  { label: "$22.00", value: "22-00" },
  { label: "$4.15", value: "4-15" },
  { label: "$2.50", value: "2-50" },
  { label: "$1.00", value: "1-00" },
  { label: "$0.35", value: "0-35" },
  { label: "$5.50", value: "5-50" },
  { label: "$15", value: "15" },
  { label: "$15.00", value: "15-00" },
  { label: "$55.00", value: "55-00" },
  { label: "$50.00", value: "50-00" },
  { label: "$4.50", value: "4-50" },
  { label: "$2.00", value: "2-00" },
  { label: "IC DGT POT", value: "ic-dgt-pot" },
  { label: "Display Module", value: "display-module" },
  { label: "IB HBA HDR", value: "ib-hba-hdr" },
  { label: "CLCC", value: "clcc" },
  { label: '"IC" <53>', value: "ic-53" },
  { label: '"Amplifiers" <158>', value: "amplifiers-158" },
  { label: '"Analog Converter" <159>', value: "analog-converter-159" },
  { label: '"Isolators" <160>', value: "isolators-160" },
  { label: "Add-on Card", value: "add-on-card" },
  { label: "FPGA MAX 10 Family", value: "fpga-max-10-family" },
  { label: "Attenuators", value: "attenuators" },
  { label: "Connnectors", value: "connnectors" },
  { label: "HDMI Transmitter", value: "hdmi-transmitter" },
  { label: "Phototransistor", value: "phototransistor" },
  { label: "connect", value: "connect" },
  { label: "ETHERNET", value: "ethernet" },
  { label: "Grid Array", value: "grid-array" },
  { label: "Landyard, S5 / S6", value: "landyard-s5-s6" },
  { label: "Development Boards", value: "development-boards" },
  { label: "Wire", value: "wire" },
  { label: "Embedded Computers", value: "embedded-computers" },
  { label: "Thermal Cut-Out", value: "thermal-cut-out" },
  { label: "Cable Conn", value: "cable-conn" },
  { label: "Board", value: "board" },
  { label: "IC REG CTRLR", value: "ic-reg-ctrlr" },
  { label: "Standoff Spacer", value: "standoff-spacer" },
  { label: "IGBT Modules", value: "igbt-modules" },
  { label: "USB Adapter", value: "usb-adapter" },
  { label: "Photocoupler", value: "photocoupler" },
  { label: "Wirewound resistor", value: "wirewound-resistor" },
  { label: "Trimmer Cap", value: "trimmer-cap" },
  { label: "Temp Sensor Digital Serial", value: "temp-sensor-digital-serial" },
  { label: "Hall Effect Sensor", value: "hall-effect-sensor" },
  { label: "Power Supplies", value: "power-supplies" },
  { label: "MOSFET N-CH", value: "mosfet-n-ch" },
  { label: "IC CURRENT TRANSMITTER", value: "ic-current-transmitter" },
  { label: "IC OPAMP DIFF", value: "ic-opamp-diff" },
  { label: "Photodiode", value: "photodiode" },
  { label: "Power Unit", value: "power-unit" },
  { label: "AC/DC", value: "ac-dc" },
  { label: "Thermsistor", value: "thermsistor" },
  { label: "USB", value: "usb" },
  { label: "Swiches", value: "swiches" },
  { label: "Transducer", value: "transducer" },
  { label: "IC OPAMP", value: "ic-opamp" },
  { label: "cover,dual USIM", value: "cover-dual-usim" },
  { label: "Sim holder", value: "sim-holder" },
  { label: "TLTC4070-0230LF", value: "tltc4070-0230-lf" },
  { label: "TLTC4070-0181LF", value: "tltc4070-0181-lf" },
  { label: "TLTC1005679-01", value: "tltc1005679-01" },
  { label: "TLTC1003748-01", value: "tltc1003748-01" },
  { label: "TLTC150973LF", value: "tltc150973-lf" },
  { label: "TLTC150896LF", value: "tltc150896-lf" },
  { label: "TLTC1015382-02", value: "tltc1015382-02" },
  { label: "TLTC1028992-01", value: "tltc1028992-01" },
  { label: "TLTC1010294-02", value: "tltc1010294-02" },
  { label: "TLTC21-050906-01", value: "tltc21-050906-01" },
  { label: "TLTC1036301-01", value: "tltc1036301-01" },
  { label: "TLTC16-130005-03", value: "tltc16-130005-03" },
  { label: "TLTC4000-0379LF", value: "tltc4000-0379-lf" },
  { label: "TLTC1005659-01", value: "tltc1005659-01" },
  { label: "TLTC150950LF", value: "tltc150950-lf" },
  { label: "TLTC220059LF", value: "tltc220059-lf" },
  { label: "TLTC150844LF", value: "tltc150844-lf" },
  { label: "TLTC150885LF", value: "tltc150885-lf" },
  { label: "TLTC16-130005-01", value: "tltc16-130005-01" },
  { label: "TLTC151253LF", value: "tltc151253-lf" },
  { label: "TLTC110281LF", value: "tltc110281-lf" },
  { label: "TLTC150389LF", value: "tltc150389-lf" },
  { label: "Closed", value: "closed" },
  { label: "Antenna", value: "antenna" },
  { label: "Couplers", value: "couplers" },
  { label: "IC GPS Module", value: "ic-gps-module" },
  { label: "Switch Fabric", value: "switch-fabric" },
  { label: "Current Sensor", value: "current-sensor" },
  { label: "Chassis", value: "chassis" },
  { label: "Ethernet Adapter", value: "ethernet-adapter" },
  { label: "tdang@omegagti.com", value: "tdang-omegagti-com" },
  { label: "SFP Transceiver", value: "sfp-transceiver" },
  { label: "cooling fan", value: "cooling-fan" },
  { label: "Motherboard", value: "motherboard" },
  { label: "DUAL PORT", value: "dual-port" },
  { label: "IC JITTER ATTENUATOR", value: "ic-jitter-attenuator" },
  { label: "Heat Sink", value: "heat-sink" },
  { label: "Bracket", value: "bracket" },
  { label: "HSK", value: "hsk" },
  { label: "IC TRANSLATION", value: "ic-translation" },
  { label: "circular connector", value: "circular-connector" },
  { label: "Retainer", value: "retainer" },
  { label: "LCD", value: "lcd" },
  { label: "Suppressor", value: "suppressor" },
  { label: "IGBT Module", value: "igbt-module" },
  { label: "Mousing Pad, Electronics", value: "mousing-pad-electronics" },
  { label: "Insulator - Converter", value: "insulator-converter" },
  { label: "Doide", value: "doide" },
  { label: "BINARY COUNTER", value: "binary-counter" },
  { label: "Single Port", value: "single-port" },
  { label: "ECC RSA AES DES MIFARE KDF CL-IF", value: "ecc-rsa-aes-des-mifare-kdf-cl-if" },
  { label: "Resister", value: "resister" },
  { label: "PCB", value: "pcb" },
  { label: "Graphic card", value: "graphic-card" },
  { label: "drives", value: "drives" },
  { label: "conductive adhesive", value: "conductive-adhesive" },
  { label: "Auxilary contact block", value: "auxilary-contact-block" },
  { label: "IC LED", value: "ic-led" },
  { label: "Optical Receiver", value: "optical-receiver" },
  { label: "IC DRVR", value: "ic-drvr" },
  { label: "SD CARD CONN", value: "sd-card-conn" },
  { label: "GPIB", value: "gpib" },
  { label: "INSPECTION WINDOW", value: "inspection-window" },
  { label: "BOXES", value: "boxes" },
  { label: "PANEL", value: "panel" },
  { label: "INDUSTRIAL LIGHTING", value: "industrial-lighting" },
  { label: "RAIL MOUNT", value: "rail-mount" },
  { label: "Absorber", value: "absorber" },
  { label: "Phototube", value: "phototube" },
  { label: "IC Sequencer", value: "ic-sequencer" },
  { label: "IC Converter", value: "ic-converter" },
  { label: "IC Switch", value: "ic-switch" },
  { label: "Mem DRAM", value: "mem-dram" },
  { label: "IC Expander", value: "ic-expander" },
  { label: "IC Volt", value: "ic-volt" },
  { label: "IC Analog", value: "ic-analog" },
  { label: "Fan", value: "fan" },
  { label: "Magnet Sensor", value: "magnet-sensor" },
  { label: "Fan Mount", value: "fan-mount" },
  { label: "Power Adapter", value: "power-adapter" },
  { label: "BJPT", value: "bjpt" },
  { label: "PCB Socket", value: "pcb-socket" },
  { label: "auxiliary contact", value: "auxiliary-contact" },
  { label: "laptop", value: "laptop" },
  { label: "hard disk", value: "hard-disk" },
  { label: "IGBT Module Trench", value: "igbt-module-trench" },
  { label: "Security Key Special", value: "security-key-special" },
  { label: "Power Monitors", value: "power-monitors" },
  { label: "Buzzer", value: "buzzer" },
  { label: "SBC", value: "sbc" },
  { label: "RF", value: "rf" },
  { label: "Speakers", value: "speakers" },
  { label: "Cable adapter", value: "cable-adapter" },
  { label: "Switch Interface Evaluation Board", value: "switch-interface-evaluation-board" },
  { label: "Intel Motherboard", value: "intel-motherboard" },
  { label: "GPU", value: "gpu" },
  { label: "PMIC", value: "pmic" },
  { label: "WiFi/Bluetooth Module", value: "wi-fi-bluetooth-module" },
  { label: "Codec", value: "codec" },
  { label: "DDR4", value: "ddr4" },
  { label: "Tranceiver", value: "tranceiver" },
  { label: "RDIMM", value: "rdimm" },
  { label: "FBGA", value: "fbga" },
  { label: "Voltage Reference", value: "voltage-reference" },
  { label: "computer Processor", value: "computer-processor" },
  { label: "Zigbee", value: "zigbee" },
  { label: "Multiplier", value: "multiplier" },
  { label: "PPGA", value: "ppga" },
  { label: "SSR", value: "ssr" },
  { label: "Socket", value: "socket" },
  { label: "Motor-Driver", value: "motor-driver" },
  { label: "Valve", value: "valve" },
  { label: "Battery Connectors", value: "battery-connectors" },
  { label: "Transponder", value: "transponder" },
  { label: "Pc Card Lan Magnetics Solutions", value: "pc-card-lan-magnetics-solutions" },
  { label: "Bridge Rectifier", value: "bridge-rectifier" },
  { label: "DC Converter", value: "dc-converter" },
  { label: "DC Power Connector", value: "dc-power-connector" },
  { label: "Quartz Crystal", value: "quartz-crystal" },
  { label: "RF Transceiver", value: "rf-transceiver" },
  { label: "SOC i.MX 8M ARM", value: "soc-i-mx-8-m-arm" },
  { label: "Board Mount Pressure Sensor", value: "board-mount-pressure-sensor" },
  { label: "NFC/RFID Read/Write", value: "nfc-rfid-read-write" },
  { label: "Cap Tant Solid 100uF", value: "cap-tant-solid-100u-f" },
  { label: "MAGNETIC SWITCH", value: "magnetic-switch" },
  { label: "ARM Cortex-32-bit", value: "arm-cortex-32-bit" },
  { label: "IMAGE SENSOR", value: "image-sensor" },
  { label: "Copper Compression", value: "copper-compression" },
  { label: "Connector Housing", value: "connector-housing" },
  { label: "SPEAKER", value: "speaker" },
  { label: "MEMORY CARD CONNECTOR", value: "memory-card-connector" },
  { label: "Key", value: "key" },
  { label: "$13.9158", value: "13-9158" },
  { label: "$12.7209", value: "12-7209" },
  { label: "$8.5762", value: "8-5762" },
  { label: "$0.8315", value: "0-8315" },
  { label: "$0.0531", value: "0-0531" },
  { label: "$3.2405", value: "3-2405" },
  { label: "$0.9920", value: "0-9920" },
  { label: "$0.8432", value: "0-8432" },
  { label: "$1.2894", value: "1-2894" },
  { label: "$4.4441", value: "4-4441" },
  { label: "$0.4807", value: "0-4807" },
  { label: "$3.8828", value: "3-8828" },
  { label: "$1.8309", value: "1-8309" },
  { label: "$0.0571", value: "0-0571" },
  { label: "$1.7598", value: "1-7598" },
  { label: "$3.4901", value: "3-4901" },
  { label: "$0.6100", value: "0-6100" },
  { label: "$0.7958", value: "0-7958" },
  { label: "$2.7952", value: "2-7952" },
  { label: "$2.7195", value: "2-7195" },
  { label: "$2.4498", value: "2-4498" },
  { label: "$2.2305", value: "2-2305" },
  { label: "Safety Relay", value: "safety-relay" },
  { label: "DC Motor", value: "dc-motor" },
  { label: "COMPLEX-EEPLD", value: "complex-eepld" },
  { label: "AC DC", value: "ac-dc" },
  { label: "SRAM", value: "sram" },
  { label: "TI", value: "ti" },
  { label: "DC/DC", value: "dc-dc" },
  { label: "Shutter", value: "shutter" },
  { label: "THYRISTOR", value: "thyristor" },
  { label: "Power Entry Module", value: "power-entry-module" },
  { label: "Touchscreens", value: "touchscreens" },
  { label: "DIGITAL IC", value: "digital-ic" },
  { label: "IC LINEAR", value: "ic-linear" },
  { label: "IC LOGIC", value: "ic-logic" },
  { label: "MEMORIES", value: "memories" },
  { label: "MAGNETICS", value: "magnetics" },
  { label: "Monitor Stand", value: "monitor-stand" },
  { label: "FIXED IND", value: "fixed-ind" },
  { label: "CONN HEADER", value: "conn-header" },
  { label: "I/O CONNECTORS", value: "i-o-connectors" },
  { label: "DC", value: "dc" },
  { label: "Thermal Imaging Camera", value: "thermal-imaging-camera" },
  { label: "AC Digital Meter", value: "ac-digital-meter" },
  { label: "Contact Probe", value: "contact-probe" },
  { label: "EMI Gasket", value: "emi-gasket" },
  { label: "SPU", value: "spu" },
  { label: "Fiber Optic", value: "fiber-optic" },
  { label: "THERMOCOUPLE CONNECTOR", value: "thermocouple-connector" },
  { label: "HDMI Extenders", value: "hdmi-extenders" },
  { label: "RAID", value: "raid" },
  { label: "GaN Amplifier", value: "ga-n-amplifier" },
  { label: "Gearbox for Servo Motor", value: "gearbox-for-servo-motor" },
  { label: "Server Board", value: "server-board" },
  { label: "Common Mode", value: "common-mode" },
  { label: "GPS Module", value: "gps-module" },
  { label: "HERMAL CAMERA + SHUTTER DTI+", value: "hermal-camera-shutter-dti" },
  { label: "Surface Mount Broadband", value: "surface-mount-broadband" },
  { label: "Sealant Coating", value: "sealant-coating" },
  { label: "330 - CPU", value: "330-cpu" },
  { label: "350 - HDD 1T SATA", value: "350-hdd-1-t-sata" },
  { label: "350 - HDD 4T SATA", value: "350-hdd-4-t-sata" },
  { label: "350 - HDD 4T SAS", value: "350-hdd-4-t-sas" },
  { label: "350 - HDD 10T SAS", value: "350-hdd-10-t-sas" },
  { label: "350 - SSD 240 SATA", value: "350-ssd-240-sata" },
  { label: "350 - SSD 480 SATA", value: "350-ssd-480-sata" },
  { label: "350 - SSD 960G SATA", value: "350-ssd-960-g-sata" },
  { label: "350 - HDD 6T SATA", value: "350-hdd-6-t-sata" },
  { label: "350 - HDD 8T SAS", value: "350-hdd-8-t-sas" },
  { label: "350 - HDD 20T SAS", value: "350-hdd-20-t-sas" },
  { label: "350 - HDD 8T SATA", value: "350-hdd-8-t-sata" },
  { label: "350 - SSD 960G NVMe", value: "350-ssd-960-g-nv-me" },
  { label: "350 - SSD 1.92T NVMe", value: "350-ssd-1-92-t-nv-me" },
  { label: "350 - SSD 3.84T NVMe", value: "350-ssd-3-84-t-nv-me" },
  { label: "350 - SSD 3.2T NVMe", value: "350-ssd-3-2-t-nv-me" },
  { label: "410 - Card, PCI, NIC etc", value: "410-card-pci-nic-etc" },
  { label: "520 - Sheetmetal & Plastic", value: "520-sheetmetal-plastic" },
  { label: "620 - Cables", value: "620-cables" },
  { label: "625 - Sys Assy (Level 6)", value: "625-sys-assy-level-6" },
  { label: "Infrared Emitter", value: "infrared-emitter" },
  { label: "TRIAC", value: "triac" },
  { label: "MIC MEMs", value: "mic-me-ms" },
]

//* Zod Schema
export const requestedItemFormSchema = z.object({
  id: z.string().min(1, { message: "Item ID is required" }),
  name: z.string().nullish(),
  mpn: z.string().nullish(),
  mfr: z.string().nullish(),
  quantity: z.coerce.number().min(1, { message: "Quantity is required" }),
  customerStandardPrice: z.coerce.number(),
  customerStandardOpportunityValue: z.coerce.number(),
})

export const requisitionFormSchema = z.object({
  id: z.string().min(1, { message: "ID is required" }),
  customerId: z.string().min(1, { message: "Company name is required" }),
  contactId: z.string().nullish(),
  customerPn: z.string().nullish(),
  requestedItems: z.array(requestedItemFormSchema).min(1, { message: "Please add at least one item" }),
  crossAlternatePn: z.string().nullish(),
  commodityType: z.string().nullish(),
  franchisePrice: z.coerce.number().nullish(),
  sapQuoteNumber: z.string().nullish(),
  quotedMpn: z.string().nullish(),
  quotedQuantity: z.string().nullish(),
  priceQuotedToCust: z.coerce.number().nullish(),
  quotedOpportunityValue: z.coerce.number().nullish(),
  date: z.date({ message: "Date is required" }),
  urgency: z.string().nullish(),
  salesPersons: z.array(z.string()).nullish(),
  brokerBuy: z.string().nullish(),
  omegaBuyers: z.array(z.string()).nullish(),
  isPurchasingInitiated: z.boolean(),
  isActiveFollowUp: z.boolean(),
  purchasingStatus: z.string().nullish(),
  result: z.string().nullish(),
  reason: z.string().nullish(),
  reqReviewResult: z.array(z.string()).nullish(),
})

//* Type
export type RequisitionForm = z.infer<typeof requisitionFormSchema>
export type RequestedItemForm = z.infer<typeof requestedItemFormSchema>
