import { z } from "zod"

export const SUPPLIER_QUOTE_STATUS_OPTIONS = [
  { label: "Quoted", value: "quoted" },
  { label: "Working", value: "working" },
  { label: "Quote Unsuitable", value: "quote-unsuitable" },
  { label: "Denied", value: "denied" },
  { label: "No Bid", value: "no-bid" },
  { label: "No Stk", value: "no-stk" },
  { label: "Higher than mkt price (Negotiating)", value: "higher-than-mkt-price-negotiating" },
  { label: "Stock Sold", value: "stock-sold" },
  { label: "PO Cancelled", value: "po-cancelled" },
]

export const SUPPLIER_QUOTE_RESULT_OPTIONS = [
  { label: "Accepted", value: "accepted" },
  { label: "Rejected", value: "rejected" },
]

export const SUPPLIER_QUOTE_SOURCING_ROUND_OPTIONS = [
  { label: "1st Round", value: "1st-round" },
  { label: "2nd Round", value: "2nd-round" },
  { label: "3rd Round", value: "3rd-round" },
  { label: "4th Round", value: "4th-round" },
  { label: "5th Round", value: "5th-round" },
  { label: "6th Round", value: "6th-round" },
  { label: "7th Round", value: "7th-round" },
  { label: "8th Round", value: "8th-round" },
  { label: "9th Round", value: "9th-round" },
  { label: "10th Round", value: "10th-round" },
]

export const SUPPLIER_QUOTE_CONTACTED_VIA_OPTIONS = [
  { label: "E-mail", value: "e-mail" },
  { label: "Phone", value: "phone" },
  { label: "Skype/IM", value: "skype-im" },
  { label: "Phone & Email", value: "phone-email" },
  { label: "Phone & Skype", value: "phone-skype" },
  { label: "Email & Skype", value: "email-skype" },
  { label: "ONLINE WEB", value: "online-web" },
  { label: "Email & WeChat", value: "email-we-chat" },
  { label: "call", value: "call" },
  { label: "New & Original", value: "new-original" },
  { label: "Phone & Email", value: "phone-email" },
  { label: "Skype", value: "skype" },
  { label: "Summer Tech", value: "summer-tech" },
  { label: "Email", value: "email" },
  { label: "Hyperdrive", value: "hyperdrive" },
  { label: "Golden Autumn", value: "golden-autumn" },
  { label: "LinkedIn", value: "linked-in" },
  { label: "Phone & Skype", value: "phone-skype" },
  { label: "In Person", value: "in-person" },
  { label: "Wechat", value: "wechat" },
  { label: "QQ", value: "qq" },
  { label: "What's App", value: "what-s-app" },
  { label: "Teams", value: "teams" },
]

export const SUPPLIER_QUOTE_LT_TO_SJC_NUMBER_OPTIONS = [
  { label: "1-2", value: "1-2" },
  { label: "2-3", value: "2-3" },
  { label: "3-4", value: "3-4" },
  { label: "3-5", value: "3-5" },
  { label: "4-5", value: "4-5" },
  { label: "5-6", value: "5-6" },
  { label: "5-7", value: "5-7" },
  { label: "6-7", value: "6-7" },
  { label: "7-8", value: "7-8" },
  { label: "8-10", value: "8-10" },
  { label: "7-10", value: "7-10" },
  { label: "10-12", value: "10-12" },
  { label: "12-15", value: "12-15" },
  { label: "1", value: "1" },
  { label: "2", value: "2" },
  { label: "3", value: "3" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
  { label: "6", value: "6" },
  { label: "7", value: "7" },
  { label: "8", value: "8" },
  { label: "9", value: "9" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
  { label: "14", value: "14" },
  { label: "15", value: "15" },
  { label: "16", value: "16" },
  { label: "17", value: "17" },
  { label: "18", value: "18" },
  { label: "19", value: "19" },
  { label: "20", value: "20" },
  { label: "21", value: "21" },
  { label: "22", value: "22" },
  { label: "23", value: "23" },
  { label: "24", value: "24" },
  { label: "25", value: "25" },
  { label: "26", value: "26" },
  { label: "27", value: "27" },
  { label: "28", value: "28" },
  { label: "29", value: "29" },
  { label: "30", value: "30" },
  { label: "31", value: "31" },
  { label: "32", value: "32" },
  { label: "33", value: "33" },
  { label: "34", value: "34" },
  { label: "35", value: "35" },
  { label: "36", value: "36" },
  { label: "37", value: "37" },
  { label: "38", value: "38" },
  { label: "39", value: "39" },
  { label: "40", value: "40" },
  { label: "41", value: "41" },
  { label: "42", value: "42" },
  { label: "43", value: "43" },
  { label: "44", value: "44" },
  { label: "45", value: "45" },
  { label: "46", value: "46" },
  { label: "47", value: "47" },
  { label: "48", value: "48" },
  { label: "49", value: "49" },
  { label: "50", value: "50" },
  { label: "51", value: "51" },
  { label: "52", value: "52" },
  { label: "53", value: "53" },
  { label: "54", value: "54" },
  { label: "55", value: "55" },
  { label: "56", value: "56" },
  { label: "57", value: "57" },
  { label: "58", value: "58" },
  { label: "59", value: "59" },
  { label: "60", value: "60" },
  { label: "61", value: "61" },
  { label: "62", value: "62" },
  { label: "63", value: "63" },
  { label: "64", value: "64" },
  { label: "65", value: "65" },
  { label: "66", value: "66" },
  { label: "67", value: "67" },
  { label: "68", value: "68" },
  { label: "69", value: "69" },
  { label: "70", value: "70" },
]

export const SUPPLIER_QUOTE_LT_TO_SJC_UOM_OPTIONS = [
  { label: "day(s)", value: "day-s" },
  { label: "week(s)", value: "week-s" },
  { label: "month(s)", value: "month-s" },
  { label: "year(s)", value: "year-s" },
]

export const SUPPLIER_QUOTE_ROHS_OPTIONS = [
  { label: "Unknown", value: "unknown" },
  { label: "Yes", value: "yes" },
  { label: "No", value: "no" },
]

//* Zod schema
export const supplierQuoteFormSchema = z.object({
  id: z.string().min(1, { message: "ID is required" }),
  date: z.date({ message: "Date is required" }),
  requisitionCode: z.coerce.number().min(1, { message: "Requisition is required" }),
  supplierCode: z.string().min(1, { message: "Supplier is required" }),
  contactId: z.string().nullish(),
  contactedVia: z.string().nullish(),
  status: z.string().min(1, { message: "Status is required" }),
  result: z.string().nullish(),
  sourcingRound: z.string().nullish(),
  followUpDate: z.date().nullish(),
  buyers: z.array(z.string()).nullish(),
  isPreferredSource: z.boolean(),
  isQuotedSource: z.boolean(),
  isShowsStock: z.boolean(),
  isShowsAvailable: z.boolean(),
  isShowsWithMfr: z.boolean(),
  isShowsWithCommodity: z.boolean(),
  isTrustedSource: z.boolean(),
  isManufacturer: z.boolean(),
  isFd: z.boolean(),
  isPreviousSourceOldStkOffer: z.boolean(),
  itemCode: z.string().min(1, { message: "Item is required" }),
  ltToSjcNumber: z.string().nullish(),
  ltToSjcUom: z.string().nullish(),
  dateCode: z.string().max(6, { message: "Date code is too long; it should be a maximum of 6 characters" }).nullish(),
  condition: z.string().nullish(),
  coo: z.string().nullish(),
  roHs: z.string().nullish(),
  quantityQuoted: z.coerce.number(),
  quantityPriced: z.coerce.number(),
  comments: z.string().nullish(),
})

//* Types
export type SupplierQuoteForm = z.infer<typeof supplierQuoteFormSchema>
